### ISSUE TITLE
published version doesn't work

### ISSUE THREAD

**Issue by Art3mK** [kcl-lang/crossplane-kcl#3]
Hey 👋

Thanks for the interesting function!  

### What happened?

Looks like there are no published function, which I can try? Not sure if that's docker image problem or my local machine setup. And I'm not sure how to list versions available.

So I'm trying to run `examples/resources/loop` with `functions.yaml` changed to:
```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: kcl-function
spec:
  package: kcllang/crossplane-kcl
```

which IIUC should run function in docker image, pulled from somewhere? 🤔 

but all I get is:

```
➜  loop git:(main) make run
crossplane beta render xr.yaml composition.yaml functions.yaml -r
crossplane: error: cannot render composite resource: cannot start Function "kcl-function": cannot start Docker container: Error response from daemon: unable to find user nonroot: no matching entries in passwd file
```

I'm running on arm64 macos with docker desktop

Thanks!

**Comment by Art3mK** [comment]
ok, looks like it's `latest` docker image from github doesn't have darwin/arm64, I guess that's why it can't start that image in container. I wasn't able to build docker images locally for that arch, but I was able to build function with go, so I can play locally 👍

**Comment by Art3mK** [comment]
@Peefy any idea how to try that in actual cluster?

```yaml
➜  k get functions kcl-function -o yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pkg.crossplane.io/v1beta1","kind":"Function","metadata":{"annotations":{},"name":"kcl-function"},"spec":{"package":"kcllang/crossplane-kcl"}}
  creationTimestamp: "2024-01-19T10:10:20Z"
  generation: 1
  name: kcl-function
  resourceVersion: "2785136"
  uid: 4a280956-4c0b-491b-bad8-9a0349a7509e
spec:
  ignoreCrossplaneConstraints: false
  package: kcllang/crossplane-kcl
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: default
  skipDependencyResolution: false
status:
  conditions:
  - lastTransitionTime: "2024-01-19T10:47:32Z"
    message: 'cannot initialize parser backend: couldn''t find "package.yaml" file
      after checking 6429 files in the archive (annotated layer: false): EOF'
    reason: UnhealthyPackageRevision
    status: "False"
    type: Healthy
  - lastTransitionTime: "2024-01-19T10:10:21Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  currentIdentifier: kcllang/crossplane-kcl
  currentRevision: kcl-function-e81ab068ba03
```

**Comment by Peefy** [comment]
Can this document help you? https://kcl-lang.io/docs/user_docs/guides/working-with-k8s/mutate-manifests/crossplane-kcl-function

**Comment by Peefy** [comment]
My message is as follows:

```yaml
$ kubectl get functions kcl-function -o yaml

apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"pkg.crossplane.io/v1beta1","kind":"Function","metadata":{"annotations":{},"name":"kcl-function"},"spec":{"package":"kcllang/crossplane-kcl"}}
  creationTimestamp: "2024-01-19T12:54:47Z"
  generation: 1
  name: kcl-function
  resourceVersion: "980"
  uid: fab2cdbf-d3f9-45be-9626-9103fa9ad36c
spec:
  ignoreCrossplaneConstraints: false
  package: kcllang/crossplane-kcl
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: default
  skipDependencyResolution: false
status:
  conditions:
  - lastTransitionTime: "2024-01-19T12:55:02Z"
    reason: UnknownPackageRevisionHealth
    status: Unknown
    type: Healthy
  - lastTransitionTime: "2024-01-19T12:55:02Z"
    reason: ActivePackageRevision
    status: "True"
    type: Installed
  currentIdentifier: kcllang/crossplane-kcl
  currentRevision: kcl-function-e81ab068ba03
```

My version is 

```yaml
$ crossplane --version

v1.14.4
```

**Comment by Art3mK** [comment]
I don't think it means function actually works, looks like your function `Healthy` status is uknown as well

```
status: Unknown
type: Healthy
```

could you check events in default namespace?
```
k get events --sort-by=.metadata.creationTimestamp -n default
```

mine function:
```
➜  k get functions
NAME           INSTALLED   HEALTHY   PACKAGE                  AGE
kcl-function   True        Unknown   kcllang/crossplane-kcl   114m
```

**Comment by Peefy** [comment]
Sorry, I've pushed a new commit https://github.com/kcl-lang/crossplane-kcl/commit/2dce197a77f6daa57ecd023afbd314bdab933f33 Could you pls help to build a local image to test it? I'm sorry, I currently don't have a computer ai this time.

**Comment by Art3mK** [comment]
ah, so it was just non existing user in the image? `crossplane beta render` works now with the docker image 👍 I guess using `USER 1000:1000` instead of non-root should be fine as well.

**Comment by Art3mK** [comment]
I see you pushed docker image, but function still doesn't work in-cluster, healthy status is unknown and I see events like these:
```
84s         Warning   ComposeResources          xapplication/xxx-xxxxxxx-vz5kk                            cannot compose resources: cannot run Composition pipeline step "normal": cannot get gRPC client connection for Function "kcl-function": cannot determine gRPC target: active FunctionRevision "kcl-function-95373156cb4d" has an empty status.endpoint
27s         Warning   ParsePackage              functionrevision/kcl-function-95373156cb4d                cannot initialize parser backend: couldn't find "package.yaml" file after checking 6429 files in the archive (annotated layer: false): EOF
```

for me it seems image is missing some config, which crossplane expecting to find from it?

**Comment by Peefy** [comment]
Can you try this image? docker.io/kcllang/crossplane-kcl

**Comment by Art3mK** [comment]
yeah, with docker image that finally works, thank you!
